# Generated by Django 4.2.2 on 2023-07-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Робот', ' Робот'), ('Variator', ' Вариатор'), ('Automatic', ' Автоматическая'), ('Manual', ' Ручная')], default='Automatic', max_length=100, verbose_name='коробка передач'),
        ),
    ]
