# Generated by Django 4.2.2 on 2023-07-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_transmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('Красный', ' Красный'), ('Белый', ' Белый'), ('Желтый', ' Желтый'), ('Черный', ' Черный'), ('Синий', ' Синий'), ('Серебристый', ' Серебристый'), ('Зеленый', ' Зеленый'), ('Серый', 'Серый')], max_length=100, verbose_name='цвет'),
        ),
        migrations.AlterField(
            model_name='car',
            name='drive_unit',
            field=models.CharField(choices=[('Передний', ' Передний'), ('Задний', ' Задний'), ('Полный', ' Полный')], max_length=100, verbose_name='привод'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Робот', ' Робот'), ('Вариатор', ' Вариатор'), ('Автоматическая', ' Автоматическая'), ('Ручная', ' Ручная')], default='Automatic', max_length=100, verbose_name='коробка передач'),
        ),
    ]
