# Generated by Django 4.2.2 on 2023-07-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_color_alter_car_drive_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('Red', ' Красный'), ('White', ' Белый'), ('Yellow', ' Желтый'), ('Black', ' Черный'), ('Blue', ' Синий'), ('Silver', ' Серебристый'), ('Green', ' Зеленый'), ('Grey', 'Серый')], max_length=100, verbose_name='цвет'),
        ),
        migrations.AlterField(
            model_name='car',
            name='drive_unit',
            field=models.CharField(choices=[('Front', ' Передний'), ('Back', ' Задний'), ('Full', ' Полный')], max_length=100, verbose_name='привод'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Robot', ' Робот'), ('Variator', ' Вариатор'), ('Automatic', ' Автоматическая'), ('Manual', ' Ручная')], default='Automatic', max_length=100, verbose_name='коробка передач'),
        ),
    ]
