# Generated by Django 4.2.2 on 2023-07-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_color_alter_car_drive_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
    ]
