# Generated by Django 4.2.2 on 2023-07-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_brand_description_car_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carimage',
            name='photo4',
        ),
        migrations.RemoveField(
            model_name='carimage',
            name='photo5',
        ),
        migrations.RemoveField(
            model_name='carimage',
            name='photo6',
        ),
        migrations.AlterField(
            model_name='carimage',
            name='photo1',
            field=models.ImageField(blank=True, upload_to='cars/', verbose_name='Фото1'),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='photo2',
            field=models.ImageField(blank=True, upload_to='cars/', verbose_name='Фото2'),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='photo3',
            field=models.ImageField(blank=True, upload_to='cars/', verbose_name='Фото3'),
        ),
    ]
