# Generated by Django 4.2.2 on 2023-07-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_remove_carimage_photo4_remove_carimage_photo5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='stock',
            field=models.BooleanField(default=True, verbose_name='наличие'),
        ),
    ]
