# Generated by Django 4.2.2 on 2023-07-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_car_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carimage',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='carimage',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='carimage',
            name='photo3',
        ),
        migrations.AddField(
            model_name='carimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='cars/', verbose_name='Картинка'),
        ),
    ]
