# Generated by Django 4.2.2 on 2023-07-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_remove_carimage_photo1_remove_carimage_photo2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='ad_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='номер объявления'),
        ),
    ]
