# Generated by Django 4.2.2 on 2023-07-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_car_ad_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='ad_number',
            field=models.IntegerField(default=None, unique=True, verbose_name='номер объявления'),
        ),
    ]
